### ISSUE TITLE
Renders very badly on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by kumarharsh** [rafaelrinaldi/pure#29]
It outputs so many boxes in the titlebar and prompt,

![sketch](https://cloud.githubusercontent.com/assets/760112/17924453/56d0f026-6a06-11e6-9977-a7184c434f53.png)

**Comment by rafaelrinaldi** [comment]
Thanks for reporting @kumarharsh, will look into that as soon as I can.

**Comment by kumarharsh** [comment]
I've looked into some other prompts too, and they also output boxes for *some* special characters, such as `⎇` and `⚡`. It seems like the default font (consolas) supports these characters, but the conhost doesn't

**Comment by oranja** [comment]
It makes sense that the global windows font supports a narrower subset of Unicode characters than the terminal itself.
@kumarharsh , it should be possible to set a different font for window titles. in Windows 10. To help diagnose the problem, do you mind setting the window font to match the terminal font? You can even try to install and use a Powerline-patched font. It might render nice geeky results regardless of this issue.

Anyway, I highly doubt that this is a `pure`, or even a `fish`, issue.

**Comment by kumarharsh** [comment]
Yes, that's what I wanted to say earlier: I think it's a conhost issue, not a pure or fish issue per se. I've tried changing fonts to 'Ubunut Mono' and even Source Code Pro, changing code pages in conemu, enabling pseudographic font, and some more things, but nothing helps.

**Comment by rafaelrinaldi** [comment]
@kumarharsh @oranja I think it's more of a unicode issue. It's not a perfect mapping between OS's. We can create a table of characters to use based on that. Should fix the issue.

**Comment by edouard-lopez** [comment]
@kumarharsh This is a BashOnWindows issue, please report to the official [BashOnWindows repo](https://github.com/Microsoft/BashOnWindows) or search for [font-related issue](https://github.com/Microsoft/BashOnWindows/issues?utf8=%E2%9C%93&q=font).
Please, drop a link to this tread when you find a solution.

**Comment by kumarharsh** [comment]
In an amusing turn of events after again switching to WSL yesterday, I found myself clicking on this issue without reading who posted it. It's still the same issue 😂

So, I don't have an update as such, since the issue is definitely with conhost. But @bitcrazed has stated that it might get fixed in a (as yet unannounced) future build of Windows.

**Comment by kumarharsh** [comment]
@bitcrazed I tried to run the fish shell in cmd.exe, and most of the issues in my screenshot above seem to have been resolved, especially the titlebar issue.

Windows console doesn't render the characters for git status, etc. which are used by pure: see here: https://github.com/rafaelrinaldi/pure/blob/master/conf.d/pure.fish#L13-L15. I presume this issue of extending the support for characters is already known to the console team (like https://github.com/Microsoft/console/issues/115)?

**Comment by bitcrazed** [comment]
Hey @kumarharsh - Glad to see that most of your issues are resolved in recent builds of Console.

The problem with symbols (esp. [emoji, CJK glyphs, etc.](https://github.com/Microsoft/console/issues/190)) not rendering correctly is due to Console still rendering text using GDI which doesn't support [font-fallback](https://docs.microsoft.com/en-us/globalization/input/font-technology#font-fallback). So, if your currently selected font doesn't have a glyph for a given Unicode code-point, and we can't use font-fallback to find a similar font that does, we have to display an "I don't know what this glyph should be" symbol.

However, we ARE working on a new DirectWrite text renderer which will support font-fallback, and will enable the Console to find & render the VAST majority of Unicode glyphs. Stay tuned! ;)

**Comment by gangsthub** [comment]
cc/ @bitcrazed, What font do you recommend (that is free) and can display correctly emojis and is monospaced for a proper use within the console? Thanks in advance!

**Comment by kumarharsh** [comment]
@gangsthub As of now, Windows console can't display emojis or some other glyphs like those used in powerline using any font. Ligatures, etc are also not supported yet. I've tried with Fira and Operator.

**Comment by bitcrazed** [comment]
@gangsthub You may have some luck with some patched fonts, but ultimately, even patched fonts won't give you broad emoji support, nor ligatures, etc. - these features require a font rendering system based on DirectWrite, not GDI which the Console currently uses.
